/**
 * Detection accuracy harness — the regression gate the old pipeline never had.
 *
 * Asserts the embedding matcher's top-1 hit rate on a REAL Switch team-preview
 * screenshot with known ground truth. To stay headless (no CLIP model download in
 * vitest), it runs against precomputed crop embeddings — generated by
 * scripts/buildJasonCropEmbeddings.ts with the exact production preprocessing
 * (segment off the red panel -> composite-on-white -> CLIP) — fed through the real
 * matchEmbedding + legal-only filter against the shipped box-embedding table.
 *
 * Bar: >= 5/6 top-1 (R7 target). The 6th slot (Rotom-Wash) is an inherent
 * near-tie with its sibling appliance formes on a tiny render, and is left to the
 * manual-override dropdown — so we assert 5/6, not 6/6. Regenerate the fixture and
 * re-check this bar whenever the table or preprocessing changes.
 */
import { describe, it, expect } from 'vitest';
import boxEmbeddings from '../../../data/boxEmbeddings.json';
import championsLegality from '../../../data/championsLegality.json';
import jasonCropEmbeddings from './fixtures/jasonCropEmbeddings.json';
import { matchEmbedding } from '../iconMatcher';
import type { BoxEmbeddingTable } from '../boxEmbeddings';
import { JASON_GROUND_TRUTH } from './fixtures/jasonTeam';

const table = boxEmbeddings as unknown as BoxEmbeddingTable;
const legalOnly = new Set(
  (championsLegality as { entries: { speciesId: string; legal: boolean }[] }).entries
    .filter((e) => e.legal)
    .map((e) => e.speciesId),
);

describe('detection accuracy on a real Switch frame', () => {
  it('matches >= 5/6 opponents top-1 (CLIP box embeddings, legal-only)', () => {
    const embeddings = jasonCropEmbeddings.embeddings as number[][];
    expect(embeddings).toHaveLength(JASON_GROUND_TRUTH.length);
    // Fixture must have been built against the shipped table.
    expect(jasonCropEmbeddings.model).toBe(table.model);
    expect(jasonCropEmbeddings.dim).toBe(table.dim);

    let top1 = 0;
    let top3 = 0;
    const lines: string[] = [];
    embeddings.forEach((emb, i) => {
      const ranked = matchEmbedding(emb, table, { legalOnly, topN: 3 });
      const rank = ranked.findIndex((c) => c.speciesId === JASON_GROUND_TRUTH[i]);
      if (rank === 0) top1++;
      if (rank >= 0 && rank < 3) top3++;
      const mark = rank === 0 ? '✓' : rank >= 0 ? '~' : '✗';
      lines.push(
        `  ${mark} slot ${i + 1}: truth=${JASON_GROUND_TRUTH[i]} -> ` +
          `[${ranked.map((r) => `${r.speciesId}:${r.confidence.toFixed(3)}`).join(', ')}]`,
      );
    });
    // eslint-disable-next-line no-console
    console.log(`\n[CLIP box embeddings] top1 ${top1}/6, top3 ${top3}/6\n${lines.join('\n')}\n`);

    expect(top1).toBeGreaterThanOrEqual(5);
  });
});
