/**
 * Champions Reg M-A item/move/ability legality overrides (R6).
 *
 * Most items/moves/abilities are unaffected by the champions mod, so unlike
 * championsLegality.json (species, a full ~1285-entry table), this is a small
 * delta table generated by scripts/buildChampionsOverrides.ts: only ids the
 * champions mod's items.ts/moves.ts/abilities.ts explicitly set `isNonstandard`
 * for.
 *
 * Legality combines this delta with the vanilla @pkmn/dex `isNonstandard`
 * (read via the `gen` singleton, src/lib/calc/gen.ts) using `'isNonstandard'
 * in override` presence checks. `isNonstandard: null` is a meaningful override
 * — it UN-bans a past-gen item/ability (e.g. Mega Stones) — and must NOT be
 * treated the same as "no override" via `??` (since `null ?? x` evaluates to
 * `x`, which would silently discard the un-ban).
 */

export interface ChampionsOverrideEntry {
  isNonstandard?: string | null;
}

/** Top-level shape of src/data/championsOverrides.json. */
export interface ChampionsOverridesTable {
  format: string;
  generatedAt: string;
  sources: { items: string; moves: string; abilities: string };
  items: Record<string, ChampionsOverrideEntry>;
  moves: Record<string, ChampionsOverrideEntry>;
  abilities: Record<string, ChampionsOverrideEntry>;
}

/**
 * Whether something is legal under the champions mod, given its vanilla
 * `isNonstandard` value and (if present) the mod's override delta for it.
 *
 * `isNonstandard` truthy (e.g. "Past") = banned; `null`/`undefined` = legal.
 * An override entry, if present for this id, wins outright — even when its
 * `isNonstandard` value is `null` (an explicit un-ban).
 */
function isLegal(
  baseIsNonstandard: string | null | undefined,
  override: ChampionsOverrideEntry | undefined,
): boolean {
  const effective =
    override && 'isNonstandard' in override ? override.isNonstandard : baseIsNonstandard;
  return effective == null;
}

export function isItemLegal(
  table: ChampionsOverridesTable,
  id: string,
  baseIsNonstandard: string | null | undefined,
): boolean {
  return isLegal(baseIsNonstandard, table.items[id]);
}

export function isMoveLegal(
  table: ChampionsOverridesTable,
  id: string,
  baseIsNonstandard: string | null | undefined,
): boolean {
  return isLegal(baseIsNonstandard, table.moves[id]);
}

export function isAbilityLegal(
  table: ChampionsOverridesTable,
  id: string,
  baseIsNonstandard: string | null | undefined,
): boolean {
  return isLegal(baseIsNonstandard, table.abilities[id]);
}
